### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by lancejjohnson** [krockode/sublime-cucumber-completion#3]
The idea for this plugin is exactly what I'm looking for. However, I can't seem to get the plugin working. I've installed through Package Control but there are no available commands in the command pallete and I cannot find anything in the menus. My guess is the plugin generates the *.expected files by scanning the features directory but there are no .expected files. 

Is there some configuration that needs to be done to use the plugin?

**Comment by krockode** [comment]
closing, assuming everything is working fine now.
